### ISSUE TITLE
docker指定env RPC_SECRET=xxxxxxx无效，仍然是默认密码

### ISSUE THREAD

**Issue by ggtony233** [P3TERX/docker-aria2-pro#171]
我使用docker-compose也不行，依旧是默认密码
```yml
version: "3.8"
services:
  aria2:
    container_name: aria2
    restart: always
    image: p3terx/aria2-pro:202209060423
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=xxxxxxx
      - UPDATE_TRACKERS=true
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - TZ=Asia/Shanghai
    ports:
      - 16888:6888
      - 16800:6800
    volumes:
      - ~/docker/apps/aria2/config:/config
      - /WestData/WestDownload:/downloads
    networks:
      mydocker:
        ipv4_address: 172.223.1.9
networks:
  mydocker:
    external: true
```

_Originally posted by @ggtony233 in https://github.com/P3TERX/Aria2-Pro-Docker/issues/5#issuecomment-2417041036_
