### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by sc1994** [P3TERX/Docker-Aria2-Pro#23]
## 异常详情
```log
01/11 16:53:51 [ERROR] CUID#26 - Exception caught while allocating file space.
aria2-pro    | Exception: [AbstractDiskWriter.cc:557] errNum=28 errorCode=9 fallocate failed. cause: No space left on device
```

## 启动配置
```yml
version: "3.3"
services:
  aria2-pro:
    container_name: aria2-pro
    image: kfwkfulq.mirror.aliyuncs.com/p3terx/aria2-pro
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=*****
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - UPDATE_TRACKERS=true
      - TZ=Asia/Shanghai
      - IPV6_MODE=true
    volumes:
      - /WD/aria2/aria2-config:/config
      - /WD/aria2/aria2-downloads:/downloads
# If you use host network mode, then no port mapping is required.
# This is your best choice when using IPv6.
    network_mode: host
    # ports:
    #   - 6800:6800
    #   - 6888:6888
    #   - 6888:6888/udp
    restart: unless-stopped
    # Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 10m
  # AriaNg is just a static web page, usually you only need to deploy on a single host.
  ariang:
    container_name: ariang
    image: p3terx/ariang
    network_mode: bridge
    ports:
      - 7000:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
```

似乎除了端口和映射目录，其他几乎没有改动。但是与i到大文件下载时候，就会出现上述异常

这是我的下载测试连接：http://repos.mia.lax-noc.com/speedtests/100gb.bin
