### ISSUE TITLE
指定环境变量RPC_SECRET不生效

### ISSUE THREAD

**Issue by 0uzu0** [P3TERX/docker-aria2-pro#5]
docker版本： 19.03.8
aria2-pro版本： latest
描述：docker run指定自定义RPC_SECRET后，实际上并没有生效，连接的时候还是使用的默认密码，但是进容器看了env，是有我自己设定的RPC_SECRET的

**Comment by P3TERX** [comment]
这个情况不应该出现，提供一下你的启动命令。

**Comment by 0uzu0** [comment]
docker run -d \
    --name aria2-pro \
    --restart unless-stopped \
    --log-opt max-size=1m \
    --network host \
    -e PUID=$UID \
    -e PGID=$GID \
    -e RPC_SECRET=XXXX \
    -e RPC_PORT=6800 \
    -e LISTEN_PORT=6888 \
    -v ~/docker/aria2/config:/config \
    -v ~/media/downloads:/downloads \
    p3terx/aria2-pro

**Comment by P3TERX** [comment]
行尾需要加`  \`（空格和反斜杠），建议你更新镜像、重建容器。

**Comment by ggtony233** [comment]
我使用docker-compose也不行，依旧是默认密码
```yml
version: "3.8"
services:
  aria2:
    container_name: aria2
    restart: always
    image: p3terx/aria2-pro:202209060423
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
      - RPC_SECRET=xxxxxxx
      - UPDATE_TRACKERS=true
      - DISK_CACHE=64M
      - IPV6_MODE=true
      - TZ=Asia/Shanghai
    ports:
      - 16888:6888
      - 16800:6800
    volumes:
      - ~/docker/apps/aria2/config:/config
      - /WestData/WestDownload:/downloads
    networks:
      mydocker:
        ipv4_address: 172.223.1.9
networks:
  mydocker:
    external: true
```
